name = "Create: Above the Seas"
author = "Void"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49c093456e69d39f2028b1997b853c76d60db5bd4531f2cede26460fdc0e01b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
