name = "Create: Above the Seas"
author = "Void"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a94d99c28b27df54823cfb40ba9e592098ebb07bad155e6a3d2e28795a14bafd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
